version: '3.8'

services:
  go-api:
      build:
        context: ./
        dockerfile: Dockerfile.dev
      volumes:
        - ./:/go/src/app #mouth volumes
      ports:
        - "5000:8080"
      command: air
